version = 0.1

[default.build.parameters]
template_file = "c:\\Users\\Andre\\Desktop\\software\\Bot\\Das\\template.yaml"
cached = true
parallel = true
use_container = true

[default.deploy.parameters]
stack_name = "Das-Bot"
resolve_s3 = true
s3_prefix = "Das-Bot"
region = "us-east-1"
profile = "dev-sso"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["DasBotFunction=796973516448.dkr.ecr.us-east-1.amazonaws.com/dasbot4d3a55c8/dasbotfunctione298f6ffrepo"]

[default.global.parameters]
region = "us-east-1"
